version: "3"

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entryPoints.websecure.address=:443
      - --entryPoints.web.address=:80
      - --log.level=DEBUG

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/etc/traefik/certs/
      - ./dynamic.yaml:/etc/traefik/dynamic/dynamic.yaml

  pictura-certamine:
    # A container that exposes an API to show its IP address
    image: pictura-certamine:0.0.0
    labels:
      # Create a router called pictura-certamine listening on the websecure entrypoint
      - "traefik.http.routers.pictura-certamine.entrypoints=websecure"
      # Force TLS
      - "traefik.http.routers.pictura-certamine.tls=true"
      # Apply a host rule specifying the domain the service will respond to
      - "traefik.http.routers.pictura-certamine.rule=Host(`concurs-captain-america.ro`)"
      # Send traffic to the container via port 8080
      - "traefik.http.services.pictura-certamine-service.loadbalancer.server.port=8080"
    environment:
      - ENV=${ENV}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - BASE_URL=${BASE_URL}
      - SESSION_REFRESH=${SESSION_REFRESH}

    volumes:
      - ./data/pictura-certamine.db:/data/pictura-certamine.db
      - ./frontend/dist:/frontend/dist
