// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BlueBox() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"blue-box\"><h1>JAK WZIĄĆ UDZIAŁ?</h1><p>Kup produkt/-y Marvela firmy Hasbro w Carrefour.  Wykonaj dowolną techniką ciekawą pracę konkursową  przedstawiającą twojego ulubionego bohatera Marvela (to może być rysunek, video, nagranie audio, opis etc.).  Zarejestruj ją klikając poniżej przycisk Weź udział.</p><p>Następnie będziesz musiał uzupełnić swoje dane i dodać  pracę, a na koniec przeczytać i potwierdzić akceptację <a href=\"/\">całego regulaminu</a>. </p><sl-button href=\"/?dialog=open\">Weź udział</sl-button><p>Konkurs przeznaczony jest dla dorosłych konsumentów końcowych zamieszkałych i/lub mających miejsce zamieszkania na terytorium Rumunii, którzy zakupią produkt Marvela firmy Hasbro w sklepach Carrefour. Pełna lista produktów warunkujących udział w konkursie znajduje się w Regulaminie. Aby wziąć udział, zostaniesz poproszony o podanie swoich danych i dodanie pracy konkursowej, a na koniec przeczytanie i potwierdzenie akceptacji <a href=\"/\">całego regulaminu</a>. </p><p>Konkurs rozpocznie się 27 stycznia 2025 r. o godzinie 09:00 i zakończy 28 marca 2025 r. o godzinie 23:59. Komisja konkursowa wyłoni zwycięzcę do 15 kwietnia 2025 r. Zwycięzca przed odebranie nagrody będzie zobowiązany do podania danych z dowodu zakupu (pamiętaj, że musisz zachować oryginał dowodu zakupu). Ze zwycięzcą skontaktujemy się mailowo. Pamiętaj, aby zawsze sprawdzać skrzynkę wiadomości-śmieci.  </p><br><p>Wartość nagrody to 40000 zł*</p><br><p>Tutaj możesz zapoznać się z <strong>pełnym regulaminem i polityką prywatności konkursu.</strong></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
