// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"footer\"><div>Śledź Disneya na:</div><div><sl-icon-button href=\"#\" target=\"_blank\" name=\"facebook\"></sl-icon-button> <sl-icon-button href=\"#\" target=\"_blank\" name=\"instagram\"></sl-icon-button> <sl-icon-button href=\"#\" target=\"_blank\" name=\"twitter-x\"></sl-icon-button> <sl-icon-button href=\"#\" target=\"_blank\" name=\"youtube\"></sl-icon-button></div><img class=\"disney-logo\" src=\"/assets/img/disney_logo.png\"><div class=\"links\"><div class=\"link-section\"><a href=\"#\">Pomoc </a> <a href=\"#\">Mapa serwisu</a> <a href=\"#\">Warunki korzystania</a> <a href=\"#\">Polityka prywatności UE</a> <a href=\"#\">Polityka Prywatności Cookie</a> <a href=\"#\">Polityka Zarządzaj ustawieniami</a> <a href=\"#\">Reklamy dopasowane</a> <a href=\"#\">Strategia podatkowa </a> <a href=\"#\">O Nas </a> <a href=\"#\">Polityka prywatnosci dla dziennikarzy </a> <a href=\"#\">The Walt Disney Company</a></div><div class=\"copyrights\">&#x24B8; Disney i podmioty powiązane. Wszelkie prawa zastrzeżone.</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
